// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/budgets": {
            "get": {
                tags: ["budget"],
                "description": "budgetの一覧を取得",
                "responses": {
                    "200": {
                        "description": "budgetの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["budget"],
                "description": "budgetの作成",
                responses: {
                    "200": {
                        "description": "create されたbudgetが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "year_id",
                        "in": "query",
                        "description": "year_id",
                        "type": "integer"
                    },
                    {
                        "name": "source_id",
                        "in": "query",
                        "description": "source_id",
                        "type": "integer"
                    }
                ],
            },
        },
        "/budgets/{id}": {
            "get": {
                tags: ["budget"],
                "description": "IDで指定されたbudgetの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "budgetの取得",
                    }
                }
            },
            "put": {
                tags: ["budget"],
                "description": "budgetの更新",
                responses: {
                    "200": {
                        "description": "更新されたbudgetが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "type": "integer"
                    },
                    {
                        "name": "year_id",
                        "in": "query",
                        "description": "year_id",
                        "type": "integer"
                    },
                    {
                        "name": "source_id",
                        "in": "query",
                        "description": "source_id",
                        "type": "integer"
                    },
                ],
            },
            "delete": {
                tags: ["budget"],
                "description": "IDを指定してbudgetの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "budgetの削除完了",
                    }
                },
            },
        },
        "/budgets/{id}/details": {
            "get": {
                tags: ["budget"],
                "description": "IDで指定されたbudgetに紐づくyearとsourceを取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "budgetに紐づくyearとsourceを取得",
                    }
                }
            },
        },
        "/activities": {
            "get": {
                tags: ["activity"],
                "description": "activitiesの一覧を取得",
                "responses": {
                    "200": {
                        "description": "activitiesの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["activity"],
                "description": "activitiesの作成",
                responses: {
                    "200": {
                        "description": "create されたactivitiestが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "sponsor_style_id",
                        "in": "query",
                        "description": "sponsor_style_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "is_done",
                        "in": "query",
                        "description": "is_done",
                        "type": "boolean"
                    },
                    {
                        "name": "sponsor_id",
                        "in": "query",
                        "description": "sponsor_id",
                        "type": "integer"
                    }
                ],
            },
        },
        "/activities/{id}": {
            "get": {
                tags: ["activity"],
                "description": "IDで指定されたactivitiesの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "activitiesの取得",
                    }
                }
            },
            "put": {
                tags: ["activity"],
                "description": "activitiesの更新",
                responses: {
                    "200": {
                        "description": "更新されたactivitiesが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "sponsor_style_id",
                        "in": "query",
                        "description": "sponsor_style_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "is_done",
                        "in": "query",
                        "description": "is_done",
                        "type": "boolean"
                    },
                    {
                        "name": "sponsor_id",
                        "in": "query",
                        "description": "sponsor_id",
                        "type": "integer"
                    },
                ],
            },
            "delete": {
                tags: ["activity"],
                "description": "IDを指定してactivitiesの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "activitiesの削除完了",
                    }
                },
            },
        },
        "/activities/details": {
            "get": {
                tags: ["activity"],
                "description": "activitiesとsponcer,sponsorStyle,userの一覧を取得",
                "responses": {
                    "200": {
                        "description": "activitiesとsponcer,sponsorStyle,userの一覧の取得",
                    }
                }
            },
        },
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "NUTFes FinanSu API",
	Description:      "FinanSu APIドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
