// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activities": {
            "get": {
                tags: ["activity"],
                "description": "activitiesの一覧を取得",
                "responses": {
                    "200": {
                        "description": "activitiesの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["activity"],
                "description": "activitiesの作成",
                responses: {
                    "200": {
                        "description": "create されたactivitiestが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "sponsor_style_id",
                        "in": "query",
                        "description": "sponsor_style_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "is_done",
                        "in": "query",
                        "description": "is_done",
                        "type": "boolean"
                    },
                    {
                        "name": "sponsor_id",
                        "in": "query",
                        "description": "sponsor_id",
                        "type": "integer"
                    }
                ],
            },
        },
        "/activities/details": {
            "get": {
                tags: ["activity"],
                "description": "activitiesとsponcer,sponsorStyle,userの一覧を取得",
                "responses": {
                    "200": {
                        "description": "activitiesとsponcer,sponsorStyle,userの一覧の取得",
                    }
                }
            },
        },
        "/activities/{id}": {
            "get": {
                tags: ["activity"],
                "description": "IDで指定されたactivitiesの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "activitiesの取得",
                    }
                }
            },
            "put": {
                tags: ["activity"],
                "description": "activitiesの更新",
                responses: {
                    "200": {
                        "description": "更新されたactivitiesが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "sponsor_style_id",
                        "in": "query",
                        "description": "sponsor_style_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "is_done",
                        "in": "query",
                        "description": "is_done",
                        "type": "boolean"
                    },
                    {
                        "name": "sponsor_id",
                        "in": "query",
                        "description": "sponsor_id",
                        "type": "integer"
                    },
                ],
            },
            "delete": {
                tags: ["activity"],
                "description": "IDを指定してactivitiesの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "activitiesの削除完了",
                    }
                },
            },
        },
        "/budgets": {
            "get": {
                tags: ["budget"],
                "description": "budgetの一覧を取得",
                "responses": {
                    "200": {
                        "description": "budgetの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["budget"],
                "description": "budgetの作成",
                responses: {
                    "200": {
                        "description": "create されたbudgetが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "year_id",
                        "in": "query",
                        "description": "year_id",
                        "type": "integer"
                    },
                    {
                        "name": "source_id",
                        "in": "query",
                        "description": "source_id",
                        "type": "integer"
                    }
                ],
            },
        },
        "/budgets/details": {
            "get": {
                tags: ["budget"],
                "description": "budgetに紐づくyearとsourceの一覧を取得",
                "responses": {
                    "200": {
                        "description": "budgetに紐づくyearとsourceの一覧を取得",
                    }
                }
            },
        },
        "/budgets/{id}": {
            "get": {
                tags: ["budget"],
                "description": "IDで指定されたbudgetの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "budgetの取得",
                    }
                }
            },
            "put": {
                tags: ["budget"],
                "description": "budgetの更新",
                responses: {
                    "200": {
                        "description": "更新されたbudgetが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "type": "integer"
                    },
                    {
                        "name": "year_id",
                        "in": "query",
                        "description": "year_id",
                        "type": "integer"
                    },
                    {
                        "name": "source_id",
                        "in": "query",
                        "description": "source_id",
                        "type": "integer"
                    },
                ],
            },
            "delete": {
                tags: ["budget"],
                "description": "IDを指定してbudgetの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "budgetの削除完了",
                    }
                },
            },
        },
        "/budgets/{id}/details": {
            "get": {
                tags: ["budget"],
                "description": "IDで指定されたbudgetに紐づくyearとsourceを取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "budgetに紐づくyearとsourceを取得",
                    }
                }
            },
        },
        "/bureaus": {
            "get": {
                tags: ["bureau"],
                "description": "bureauの一覧を取得",
                "responses": {
                    "200": {
                        "description": "bureauの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["bureau"],
                "description": "bureauの作成",
                responses: {
                    "200": {
                        "description": "create されたbureauが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name",
                        "required": true,
                        "type": "string"
                    },
                ],
            },
        },
        "/bureaus/{id}": {
            "get": {
                tags: ["bureau"],
                "description": "IDで指定されたbureauの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "bureauの取得",
                    }
                }
            },
            "put": {
                tags: ["bureau"],
                "description": "bureauの更新",
                responses: {
                    "200": {
                        "description": "更新されたbureauが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name",
                        "type": "string"
                    },
                ],
            },
            "delete": {
                tags: ["bureau"],
                "description": "IDを指定してbureauの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "bureauの削除完了",
                    }
                },
            },
        },
        "/fund_informations": {
            "get": {
                tags: ["fund_information"],
                "description": "fund_informationの一覧を取得",
                "responses": {
                    "200": {
                        "description": "fund_informationの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["fund_information"],
                "description": "fund_informationの作成",
                responses: {
                    "200": {
                        "description": "create されたfund_informationが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "teacher_id",
                        "in": "query",
                        "description": "teacher_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "remark",
                        "in": "query",
                        "description": "remark",
                        "type": "string"
                    },
                    {
                        "name": "is_first_check",
                        "in": "query",
                        "description": "is_first_check",
                        "type": "boolean"
                    },
                    {
                        "name": "is_last_check",
                        "in": "query",
                        "description": "is_last_check",
                        "type": "boolean"
                    }
                ],
            },
        },
        "/fund_informations/details": {
            "get": {
                tags: ["fund_information"],
                "description": "fund_informationに紐づくteacherとuserの一覧を取得",
                "responses": {
                    "200": {
                        "description": "fund_informationに紐づくteacherとuserの一覧を取得",
                    }
                }
            },
        },
        "/fund_informations/{id}": {
            "get": {
                tags: ["fund_information"],
                "description": "IDで指定されたfund_informationの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "fund_informationの取得",
                    }
                }
            },
            "put": {
                tags: ["fund_information"],
                "description": "fund_informationの更新",
                responses: {
                    "200": {
                        "description": "更新されたfund_informationが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "teacher_id",
                        "in": "query",
                        "description": "teacher_id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "price",
                        "in": "query",
                        "description": "price",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "remark",
                        "in": "query",
                        "description": "remark",
                        "type": "string"
                    },
                    {
                        "name": "is_first_check",
                        "in": "query",
                        "description": "is_first_check",
                        "type": "boolean"
                    },
                    {
                        "name": "is_last_check",
                        "in": "query",
                        "description": "is_last_check",
                        "type": "boolean"
                    }
                ],
            },
            "delete": {
                tags: ["fund_information"],
                "description": "IDを指定してfund_informationの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "fund_informationの削除完了",
                    }
                },
            },
        },
        "/fund_informations/{id}/details": {
            "get": {
                tags: ["fund_information"],
                "description": "IDで指定されたfund_informatinに紐づくteacherとuserを取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "fund_informatinに紐づくteacherとuserを取得",
                    }
                }
            },
        },
        "/purchaseorders": {
            "get": {
                tags: ["purchaseorder"],
                "description": "purchaseorderの一覧を取得",
                "responses": {
                    "200": {
                        "description": "purchaseorderの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["purchaseorder"],
                "description": "purchaseorderの作成",
                responses: {
                    "200": {
                        "description": "create されたpurchaseorderが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "deadline",
                        "in": "query",
                        "description": "deadline",
                        "type": "string"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "finance_check",
                        "in": "query",
                        "description": "finance_check",
                        "type": "boolean"
                    }
                ],
            },
        },
        "/purchaseorders/details": {
            "get": {
                tags: ["purchaseorder"],
                "description": "purchaseorderに紐づくuserとitemの一覧を取得",
                "responses": {
                    "200": {
                        "description": "bpurchaseorderに紐づくuserとitemの一覧を取得",
                    }
                }
            },
        },
        "/purchaseorders/{id}": {
            "get": {
                tags: ["purchaseorder"],
                "description": "IDで指定されたpurchaseorderの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "purchaseorderの取得",
                    }
                }
            },
            "put": {
                tags: ["purchaseorder"],
                "description": "purchaseorderの更新",
                responses: {
                    "200": {
                        "description": "更新されたpurchaseorderが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "deadline",
                        "in": "query",
                        "description": "deadline",
                        "type": "string"
                    },
                    {
                        "name": "user_id",
                        "in": "query",
                        "description": "user_id",
                        "type": "integer"
                    },
                    {
                        "name": "finance_check",
                        "in": "query",
                        "description": "finance_check",
                        "type": "boolean"
                    },
                ],
            },
            "delete": {
                tags: ["purchaseorder"],
                "description": "IDを指定してpurchaseorderの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "purchaseorderの削除完了",
                    }
                },
            },
        },
        "/purchaseorders/{id}/details": {
            "get": {
                tags: ["purchaseorder"],
                "description": "IDで指定されたpurchaseorderに紐づくuserとitemを取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "IDで指定されたpurchaseorderに紐づくuserとitemを取得",
                    }
                }
            },
        },
        "/years": {
            "get": {
                tags: ["year"],
                "description": "yearの一覧の取得",
                "responses": {
                    "200": {
                        "description": "yearの一覧を取得",
                    }
                }
            },
            "post": {
                tags: ["year"],
                "description": "yearの作成",
                responses: {
                    "200": {
                        "description": "作成されたyearが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "year",
                        "in": "query",
                        "description": "year",
                        "required": true,
                        "type": "integer"
                    }
                ],
            },
        },
        "/years/{id}": {
            "get": {
                tags: ["year"],
                "description": "IDで指定されたyearの取得",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "yearの取得",
                    }
                }
            },
            "put": {
                tags: ["year"],
                "description": "yearの更新",
                responses: {
                    "200": {
                        "description": "更新されたyearが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    },
                    {
                        "name": "year",
                        "in": "query",
                        "description": "year",
                        "required": true,
                        "type": "integer"
                    }
                ],
            },
            "delete": {
                tags: ["year"],
                "description": "IDを指定してyearの削除",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id",
                        "required": true,
                        "type": "integer"
                    }
                ],
                responses: {
                    "200": {
                        "description": "yearの削除完了",
                    }
                },
            },
        },
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "NUTFes FinanSu API",
	Description:      "FinanSu APIドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
