linters-settings:
  unused:
    check-struct: true
    check-variables: true
  revive:
    severity: warning

linters:
  enable:
    - unused
    - revive
  disable:
    - varcheck
    - golint
    - structcheck

run:
  timeout: 5m
