services:
  view:
    build: ./view
    container_name: "nutfes-finansu-view"
    volumes:
      - ./view:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
      - "6006:6006"
    stdin_open: true
    environment:
      NEXT_PUBLIC_APP_ENV: development
      NEXT_PUBLIC_ENDPOINT: minio
      NEXT_PUBLIC_PORT: 9000
      NEXT_PUBLIC_BUCKET_NAME: finansu
      NEXT_PUBLIC_MINIO_ENDPONT: http://localhost:9000
      NEXT_PUBLIC_ACCESS_KEY: user
      NEXT_PUBLIC_SECRET_KEY: password
      RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
    tty: true

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: "nutfes-finansu-api"
    volumes:
      - ./api:/app
      - ./openapi:/openapi
    environment:
      RESET_PASSWORD_URL: "http://localhost:3000/reset_password"
    #シェルスクリプトを実行するコマンド
    command: "./start.sh"
    env_file: ["./finansu.env"]
    ports:
      - "1323:1323"
    stdin_open: true
    tty: true
