version: "3"
services:
  db:
    image: mysql:8.0
    container_name: "nutfes-finansu-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: finansu_db
      MYSQL_USER: finansu
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    restart: always

  view:
    build: ./view
    container_name: "nutfes-finansu-view"
    volumes:
      - ./view:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      NEXT_PUBLIC_ENDPOINT: minio
      NEXT_PUBLIC_PORT: 9000
      NEXT_PUBLIC_BUCKET_NAME: finansu
      NEXT_PUBLIC_MINIO_ENDPONT: http://localhost:9000
    tty: true

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: "nutfes-finansu-api"
    volumes:
      - ./api:/app
    environment:
      NUTMEG_MAIL_SENDER: "nutfes.finansu@gmail.com"
      NUTMEG_MAIL_PASSWORD: "xmifwkbpiybisqto"
      RESET_PASSWORD_URL: "http://localhost:3000/reset_password"
    #シェルスクリプトを実行するコマンド
    command: "./start.sh"
    ports:
      - "1323:1323"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_started

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./tmp/minio/data:/data
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
