version: "3"
services:
  db:
    image: mysql:8.0
    container_name: "nutfes-finansu-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: finansu_db
      MYSQL_USER: finansu
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    restart: always

  view:
    build:
      context: ./view
      dockerfile: local-prod.Dockerfile
    container_name: "nutfes-finansu-view"
    command: "npm run start"
    ports: ["3000:3000"]
    depends_on: ["api"]

  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    container_name: "nutfes-finansu-api"
    volumes: ["./api:/app"]
    ports: ["1323:1323"]
    env_file: ["./api/env/dev.env"]
    environment:
      ENV: "production"
      NUTMEG_MAIL_SENDER: "nutfes.finansu@gmail.com"
      NUTMEG_MAIL_PASSWORD: "xmifwkbpiybisqto"
      RESET_PASSWORD_URL: "http://localhost:3000/reset_password"
    depends_on:
      db:
        condition: service_started

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./tmp/minio/data:/data
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
