services:
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "nutfes-finansu-web"
    volumes: ["./web/prod:/home/nonroot/.cloudflared"]
    command: tunnel run

  view:
    build: "./view"
    container_name: "nutfes-finansu-view"
    volumes: ["./view:/app"]
    command: "npm run start"
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_APP_ENV: "production"
    depends_on: ["api"]

  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    container_name: "nutfes-finansu-api"
    volumes: ["./api:/app"]
    command: "go run main.go"
    env_file: ["./finansu.env"]
    ports: ["1323:1323"]
    environment:
      RESET_PASSWORD_URL: "https://finansu.nutfes.net/reset_password"
