version: '3'
services:
  view:
    build: ./view
    container_name: "nutfes-finansu-view"
    volumes:
      - ./view:/app
    command: "npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
