version: '3'
services:
  view:
    build: ./view
    container_name: "nutfes-finansu-view"
    volumes:
      - ./view:/app
    command: sh -c "cd next-project && npm run dev"
    ports:
      - "3000:3000"
