version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "nutfes-finansu-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      # - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: finansu_db
      MYSQL_USER: finansu
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    restart: always

  view:
    build: ./view
    container_name: "nutfes-finansu-view"
    volumes:
      - ./view:/app
    command: "npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  api:
    build: ./api
    container_name: "nutfes-finansu-api"
    volumes:
      - ./api:/app
    command: go run cmd/main.go
      # command: "air"
    ports:
      - "1323:1323"
    stdin_open: true
    tty: true
      # depends_on:
      #   db:
      #     condition: service_started

