// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/NUTFes/FinanSu/api/drivers/db"
	"github.com/NUTFes/FinanSu/api/drivers/mc"
	"github.com/NUTFes/FinanSu/api/drivers/server"
	"github.com/NUTFes/FinanSu/api/externals/handler"
	"github.com/NUTFes/FinanSu/api/externals/repository"
	"github.com/NUTFes/FinanSu/api/externals/repository/abstract"
	"github.com/NUTFes/FinanSu/api/internals/usecase"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

// InitializeServer - Wireで生成される関数
func InitializeServer() (*ServerComponents, error) {
	client, err := ProvideDBClient()
	if err != nil {
		return nil, err
	}
	crud := ProvideCrud(client)
	activityRepository := repository.NewActivityRepository(client, crud)
	activityUseCase := usecase.NewActivityUseCase(activityRepository)
	activityInformationRepository := repository.NewActivityInformationsRepository(client, crud)
	activityInformationUseCase := usecase.NewActivityInformationUseCase(activityInformationRepository)
	activityStyleRepository := repository.NewActivityStyleRepository(client, crud)
	activityStyleUseCase := usecase.NewActivityStyleUseCase(activityStyleRepository)
	bureauRepository := repository.NewBureauRepository(client, crud)
	bureauUseCase := usecase.NewBureauUseCase(bureauRepository)
	buyReportRepository := repository.NewBuyReportRepository(client, crud)
	transactionRepository := repository.NewTransactionRepository(client, crud)
	mcClient, err := ProvideMinioClient()
	if err != nil {
		return nil, err
	}
	objectHandleRepository := repository.NewObjectHandleRepository(mcClient)
	incomeExpenditureManagementRepository := repository.NewIncomeExpenditureManagementRepository(client, crud)
	buyReportUseCase := usecase.NewBuyReportUseCase(buyReportRepository, transactionRepository, objectHandleRepository, incomeExpenditureManagementRepository)
	departmentRepository := repository.NewDepartmentRepository(client, crud)
	departmentUseCase := usecase.NewDepartmentUseCase(departmentRepository)
	divisionRepository := repository.NewDivisionRepository(client, crud)
	divisionUseCase := usecase.NewDivisionUseCase(divisionRepository)
	festivalItemRepository := repository.NewFestivalItemRepository(client, crud)
	festivalItemUseCase := usecase.NewFestivalItemUseCase(festivalItemRepository, transactionRepository)
	financialRecordRepository := repository.NewFinancialRecordRepository(client, crud)
	financialRecordUseCase := usecase.NewFinancialRecordUseCase(financialRecordRepository)
	incomeRepository := repository.NewIncomeRepository(client, crud)
	incomeUseCase := usecase.NewIncomeUseCase(incomeRepository, incomeExpenditureManagementRepository, transactionRepository)
	incomeExpenditureManagementUseCase := usecase.NewIncomeExpenditureManagementUseCase(incomeExpenditureManagementRepository)
	mailAuthRepository := repository.NewMailAuthRepository(client, crud)
	sessionRepository := repository.NewSessionRepository(client)
	mailAuthUseCase := usecase.NewMailAuthUseCase(mailAuthRepository, sessionRepository)
	objectUploadUseCase := usecase.NewObjectUploadUseCase(objectHandleRepository)
	passwordResetTokenRepository := repository.NewPasswordResetTokenRepository(client, crud)
	userRepository := repository.NewUserRepository(client, crud)
	passwordResetTokenUseCase := usecase.NewPasswordResetTokenUseCase(passwordResetTokenRepository, userRepository, mailAuthRepository)
	sponsorRepository := repository.NewSponsorRepository(client, crud)
	sponsorUseCase := usecase.NewSponsorUseCase(sponsorRepository)
	sponsorStyleRepository := repository.NewSponsorStyleRepository(client, crud)
	sponsorStyleUseCase := usecase.NewSponsorStyleUseCase(sponsorStyleRepository)
	teacherRepository := repository.NewTeacherRepository(client, crud)
	teacherUseCase := usecase.NewTeacherUseCase(teacherRepository)
	userUseCase := usecase.NewUserUseCase(userRepository, sessionRepository)
	yearRepository := repository.NewYearRepository(client, crud)
	yearUseCase := usecase.NewYearUseCase(yearRepository)
	sponsorshipActivityRepository := repository.NewSponsorshipActivityRepository(client, crud)
	sponsorshipActivityUseCase := usecase.NewSponsorshipActivityUseCase(sponsorshipActivityRepository, transactionRepository)
	handlerHandler := handler.NewHandler(activityUseCase, activityInformationUseCase, activityStyleUseCase, bureauUseCase, buyReportUseCase, departmentUseCase, divisionUseCase, festivalItemUseCase, financialRecordUseCase, incomeUseCase, incomeExpenditureManagementUseCase, mailAuthUseCase, objectUploadUseCase, passwordResetTokenUseCase, sponsorUseCase, sponsorStyleUseCase, teacherUseCase, userUseCase, yearUseCase, sponsorshipActivityUseCase)
	echo := ProvideServer(handlerHandler)
	serverComponents := ProvideServerComponents(client, echo)
	return serverComponents, nil
}

// wire.go:

// ServerComponents はサーバーコンポーネントをまとめる構造体
type ServerComponents struct {
	Client db.Client
	Echo   *echo.Echo
}

// ProvideDBClient - DB接続のProvider
func ProvideDBClient() (db.Client, error) {
	return db.ConnectMySQL()
}

// ProvideMinioClient - MinioClientのProvider
func ProvideMinioClient() (mc.Client, error) {
	return mc.InitMinioClient()
}

// ProvideCrud - AbstractCrudのProvider
func ProvideCrud(client db.Client) abstract.Crud {
	return abstract.NewCrud(client)
}

// ProvideServer - ServerのProvider
func ProvideServer(h *handler.Handler) *echo.Echo {
	return server.RunServer(h)
}

// ProvideServerComponents - ServerComponentsのProvider
func ProvideServerComponents(client db.Client, echo2 *echo.Echo) *ServerComponents {
	return &ServerComponents{
		Client: client,
		Echo:   echo2,
	}
}
