// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/NUTFes/FinanSu/api/drivers/db"
	"github.com/NUTFes/FinanSu/api/drivers/mc"
	"github.com/NUTFes/FinanSu/api/drivers/server"
	"github.com/NUTFes/FinanSu/api/externals/controller"
	"github.com/NUTFes/FinanSu/api/externals/repository"
	"github.com/NUTFes/FinanSu/api/externals/repository/abstract"
	"github.com/NUTFes/FinanSu/api/internals/usecase"
	"github.com/NUTFes/FinanSu/api/router"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

// InitializeServer - Wireで生成される関数
func InitializeServer() (*ServerComponents, error) {
	client, err := ProvideDBClient()
	if err != nil {
		return nil, err
	}
	crud := ProvideCrud(client)
	activityRepository := repository.NewActivityRepository(client, crud)
	activityUseCase := usecase.NewActivityUseCase(activityRepository)
	activityController := controller.NewActivityController(activityUseCase)
	activityInformationRepository := repository.NewActivityInformationsRepository(client, crud)
	activityInformationUseCase := usecase.NewActivityInformationUseCase(activityInformationRepository)
	activityInformationController := controller.NewActivityInformationController(activityInformationUseCase)
	activityStyleRepository := repository.NewActivityStyleRepository(client, crud)
	activityStyleUseCase := usecase.NewActivityStyleUseCase(activityStyleRepository)
	activityStyleController := controller.NewActivityStyleController(activityStyleUseCase)
	budgetRepository := repository.NewBudgetRepository(client, crud)
	budgetUseCase := usecase.NewBudgetUseCase(budgetRepository)
	budgetController := controller.NewBudgetController(budgetUseCase)
	bureauRepository := repository.NewBureauRepository(client, crud)
	bureauUseCase := usecase.NewBureauUseCase(bureauRepository)
	bureauController := controller.NewBureauController(bureauUseCase)
	buyReportRepository := repository.NewBuyReportRepository(client, crud)
	transactionRepository := repository.NewTransactionRepository(client, crud)
	mcClient, err := ProvideMinioClient()
	if err != nil {
		return nil, err
	}
	objectHandleRepository := repository.NewObjectHandleRepository(mcClient)
	incomeExpenditureManagementRepository := repository.NewIncomeExpenditureManagementRepository(client, crud)
	buyReportUseCase := usecase.NewBuyReportUseCase(buyReportRepository, transactionRepository, objectHandleRepository, incomeExpenditureManagementRepository)
	buyReportController := controller.NewBuyReportController(buyReportUseCase)
	departmentRepository := repository.NewDepartmentRepository(client, crud)
	departmentUseCase := usecase.NewDepartmentUseCase(departmentRepository)
	departmentController := controller.NewDepartmentController(departmentUseCase)
	divisionRepository := repository.NewDivisionRepository(client, crud)
	divisionUseCase := usecase.NewDivisionUseCase(divisionRepository)
	divisionController := controller.NewDivisionController(divisionUseCase)
	expenseRepository := repository.NewExpenseRepository(client, crud)
	expenseUseCase := usecase.NewExpenseUseCase(expenseRepository)
	expenseController := controller.NewExpenseController(expenseUseCase)
	festivalItemRepository := repository.NewFestivalItemRepository(client, crud)
	festivalItemUseCase := usecase.NewFestivalItemUseCase(festivalItemRepository, transactionRepository)
	festivalItemController := controller.NewFestivalItemController(festivalItemUseCase)
	financialRecordRepository := repository.NewFinancialRecordRepository(client, crud)
	financialRecordUseCase := usecase.NewFinancialRecordUseCase(financialRecordRepository)
	financialRecordController := controller.NewFinancialRecordController(financialRecordUseCase)
	fundInformationRepository := repository.NewFundInformationRepository(client, crud)
	fundInformationUseCase := usecase.NewFundInformationUseCase(fundInformationRepository)
	fundInformationController := controller.NewFundInformationController(fundInformationUseCase)
	healthcheckController := controller.NewHealthCheckController()
	incomeRepository := repository.NewIncomeRepository(client, crud)
	incomeUseCase := usecase.NewIncomeUseCase(incomeRepository, incomeExpenditureManagementRepository, transactionRepository)
	incomeController := controller.NewIncomeController(incomeUseCase)
	incomeExpenditureManagementUseCase := usecase.NewIncomeExpenditureManagementUseCase(incomeExpenditureManagementRepository)
	incomeExpenditureManagementController := controller.NewIncomeExpenditureManagementController(incomeExpenditureManagementUseCase)
	mailAuthRepository := repository.NewMailAuthRepository(client, crud)
	sessionRepository := repository.NewSessionRepository(client)
	mailAuthUseCase := usecase.NewMailAuthUseCase(mailAuthRepository, sessionRepository)
	mailAuthController := controller.NewMailAuthController(mailAuthUseCase)
	objectUploadUseCase := usecase.NewObjectUploadUseCase(objectHandleRepository)
	objectUploadController := controller.NewObjectUploadController(objectUploadUseCase)
	passwordResetTokenRepository := repository.NewPasswordResetTokenRepository(client, crud)
	userRepository := repository.NewUserRepository(client, crud)
	passwordResetTokenUseCase := usecase.NewPasswordResetTokenUseCase(passwordResetTokenRepository, userRepository, mailAuthRepository)
	passwordResetTokenController := controller.NewPasswordResetTokenController(passwordResetTokenUseCase)
	purchaseItemRepository := repository.NewPurchaseItemRepository(client, crud)
	purchaseItemUseCase := usecase.NewPurchaseItemUseCase(purchaseItemRepository)
	purchaseItemController := controller.NewPurchaseItemController(purchaseItemUseCase)
	purchaseOrderRepository := repository.NewPurchaseOrderRepository(client, crud)
	purchaseOrderUseCase := usecase.NewPurchaseOrderUseCase(purchaseOrderRepository, bureauRepository, expenseRepository)
	purchaseOrderController := controller.NewPurchaseOrderController(purchaseOrderUseCase)
	purchaseReportRepository := repository.NewPurchaseReportRepository(client, crud)
	purchaseReportUseCase := usecase.NewPurchaseReportUseCase(purchaseReportRepository)
	purchaseReportController := controller.NewPurchaseReportController(purchaseReportUseCase)
	receiptRepository := repository.NewReceiptRepository(client, crud)
	receiptUseCase := usecase.NewReceiptUseCase(receiptRepository)
	receiptController := controller.NewReceiptController(receiptUseCase)
	sourceRepository := repository.NewSourceRepository(client, crud)
	sourceUseCase := usecase.NewSourceUseCase(sourceRepository)
	sourceController := controller.NewSourceController(sourceUseCase)
	sponsorRepository := repository.NewSponsorRepository(client, crud)
	sponsorUseCase := usecase.NewSponsorUseCase(sponsorRepository)
	sponsorController := controller.NewSponsorController(sponsorUseCase)
	sponsorStyleRepository := repository.NewSponsorStyleRepository(client, crud)
	sponsorStyleUseCase := usecase.NewSponsorStyleUseCase(sponsorStyleRepository)
	sponsorStyleController := controller.NewSponsorStyleController(sponsorStyleUseCase)
	teacherRepository := repository.NewTeacherRepository(client, crud)
	teacherUseCase := usecase.NewTeacherUseCase(teacherRepository)
	teacherController := controller.NewTeacherController(teacherUseCase)
	userUseCase := usecase.NewUserUseCase(userRepository, sessionRepository)
	userController := controller.NewUserController(userUseCase)
	yearRepository := repository.NewYearRepository(client, crud)
	yearUseCase := usecase.NewYearUseCase(yearRepository)
	yearController := controller.NewYearController(yearUseCase)
	router := ProvideRouter(activityController, activityInformationController, activityStyleController, budgetController, bureauController, buyReportController, departmentController, divisionController, expenseController, festivalItemController, financialRecordController, fundInformationController, healthcheckController, incomeController, incomeExpenditureManagementController, mailAuthController, objectUploadController, passwordResetTokenController, purchaseItemController, purchaseOrderController, purchaseReportController, receiptController, sourceController, sponsorController, sponsorStyleController, teacherController, userController, yearController)
	echo := ProvideServer(router)
	serverComponents := ProvideServerComponents(client, echo)
	return serverComponents, nil
}

// wire.go:

// ServerComponents はサーバーコンポーネントをまとめる構造体
type ServerComponents struct {
	Client db.Client
	Echo   *echo.Echo
}

// ProvideDBClient - DB接続のProvider
func ProvideDBClient() (db.Client, error) {
	return db.ConnectMySQL()
}

// ProvideMinioClient - MinioClientのProvider
func ProvideMinioClient() (mc.Client, error) {
	return mc.InitMinioClient()
}

// ProvideCrud - AbstractCrudのProvider
func ProvideCrud(client db.Client) abstract.Crud {
	return abstract.NewCrud(client)
}

// ProvideRouter - Router構築のProvider
func ProvideRouter(
	activityController controller.ActivityController,
	activityInformationController controller.ActivityInformationController,
	activityStyleController controller.ActivityStyleController,
	budgetController controller.BudgetController,
	bureauController controller.BureauController,
	buyReportController controller.BuyReportController,
	departmentController controller.DepartmentController,
	divisionController controller.DivisionController,
	expenseController controller.ExpenseController,
	festivalItemController controller.FestivalItemController,
	financialRecordController controller.FinancialRecordController,
	fundInformationController controller.FundInformationController,
	healthcheckController controller.HealthcheckController,
	incomeController controller.IncomeController,
	incomeExpenditureManagementController controller.IncomeExpenditureManagementController,
	mailAuthController controller.MailAuthController,
	objectUploadController controller.ObjectUploadController,
	passwordResetTokenController controller.PasswordResetTokenController,
	purchaseItemController controller.PurchaseItemController,
	purchaseOrderController controller.PurchaseOrderController,
	purchaseReportController controller.PurchaseReportController,
	receiptController controller.ReceiptController,
	sourceController controller.SourceController,
	sponsorController controller.SponsorController,
	sponsorStyleController controller.SponsorStyleController,
	teacherController controller.TeacherController,
	userController controller.UserController,
	yearController controller.YearController,
) router.Router {
	return router.NewRouter(
		activityController,
		activityInformationController,
		activityStyleController,
		budgetController,
		bureauController,
		buyReportController,
		departmentController,
		divisionController,
		expenseController,
		festivalItemController,
		financialRecordController,
		fundInformationController,
		healthcheckController,
		incomeController,
		incomeExpenditureManagementController,
		mailAuthController,
		objectUploadController,
		passwordResetTokenController,
		purchaseItemController,
		purchaseOrderController,
		purchaseReportController,
		receiptController,
		sourceController,
		sponsorController,
		sponsorStyleController,
		teacherController,
		userController,
		yearController,
	)
}

// ProvideServer - ServerのProvider
func ProvideServer(router2 router.Router) *echo.Echo {
	return server.RunServer(router2)
}

// ProvideServerComponents - ServerComponentsのProvider
func ProvideServerComponents(client db.Client, echo2 *echo.Echo) *ServerComponents {
	return &ServerComponents{
		Client: client,
		Echo:   echo2,
	}
}
