import type { NextPage } from 'next';
import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { Table, Thead, Tbody, Tfoot, Tr, Th, Td, TableCaption } from '@chakra-ui/react';
import { Center } from '@chakra-ui/react';
import Header from 'src/components/Header';

const BudgetList: NextPage = () => {
  const budgetList = [
    {
      id: 1,
      name: '教育振興会費',
      value: 1200000,
    },
    {
      id: 2,
      name: '同窓会費',
      value: 200000,
    },
    {
      id: 3,
      name: '企業協賛金',
      value: 0,
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <hr />
      <Center>
        <Box w='60%' mt='5' boxShadow='md' rounded='lg'>
          <Box mt='3' ml='5' fontSize='1.2em'>
            予算一覧
          </Box>
          <Box p='5' mt='2'>
            <Table variant='simple'>
              <Thead>
                <Tr>
                  <Th>
                    <Center>項目</Center>
                  </Th>
                  <Th>
                    <Center>予算金額</Center>
                  </Th>
                </Tr>
              </Thead>
              <Tbody>
                {budgetList.map((budgetItem) => (
                  <Tr key={budgetItem.id}>
                    <Td>
                      <Center>{budgetItem.name}</Center>
                    </Td>
                    <Td>
                      <Center>{budgetItem.value}</Center>
                    </Td>
                  </Tr>
                ))}
              </Tbody>
              <Tfoot>
                <Tr>
                  <Th>
                    <Center>合計</Center>
                  </Th>
                  <Th>
                    <Center>140000</Center>
                  </Th>
                </Tr>
              </Tfoot>
            </Table>
          </Box>
        </Box>
      </Center>
    </div>
  );
};

export default BudgetList;
