use finansu_db

CREATE TABLE teacher_rooms (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  building_id INT(10) UNSIGNED,
  room_number INT(10) UNSIGNED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (building_id) REFERENCES buildings(id)
);
