use finansu_db

INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('岩橋 政宏', '教授', 1, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小野 浩司', '教授', 1, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('木村 宗弘', '教授', 1, 3, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大石 潔', '教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('三浦 友史', '教授', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('坪根 正', '教授', 1, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('田中 久仁彦', '教授', 1,7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('宮崎 敏昌', '教授', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('岡元 智一郎', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('圓道 知博', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('杉田 泰則', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鵜沼 毅也', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('佐々木 友之', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('玉山 泰宏', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('南部 功夫', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('和田森 直', '助教', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('横倉 勇希', '助教授', 1, 16, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 一匡', '助教', 1, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('白清 学', '助教', 1, 21, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('渡部 康平', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('坂本 盛嗣', '准教授', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('原川 良介', '助教', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('眞田 亜紀子', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('日高 勇気', '准教授', 1, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('LE THI TINH MINH', '准教授', 1, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('TRAN PHUONG THAO', '助教', 1, 16, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('圓山 由子', '助教', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('金井 綾香', '助教', 1, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('渡辺 大貴', '助教', 1, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('滝本 浩一', '教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('政井 英司', '教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('城所 俊一', '教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('本多 元', '教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 祥司', '教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('志田 洋介', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('木村 悟隆', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高原 美規', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('霜田 靖', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('佐藤 武史', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山本 麻希', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('西村 泰介', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('笠井 大輔', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('桑原 敬司', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('藤原 郁子', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('上村 直史', '准教授', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('内山 尚志', '助教', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('早乙女 友規', '助教', 2, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('斎藤 秀俊', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('竹中 克彦', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('前川 博史', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('石橋 隆幸', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('今久保 達郎', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('梅田 実', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('河原 成元', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('伊藤 治彦', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('内田 希', '准教授', 2, 27, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('齊藤 信雄', '准教授', 2, 24, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('本間 剛', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 由紀子', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('多賀谷 基博', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('白仁田 沙代子', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('西川 雅美', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('船津 麻美', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小松 啓志', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('戸田 智之', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('シリポーン タオガァオ', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松田 翔風', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('張 田原', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('斎藤 秀俊', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('竹中 克彦', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('前川 博史', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('石橋 隆幸', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('今久保 達郎', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('梅田 実', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('河原 成元', '教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('伊藤 治彦', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('内田 希', '准教授', 2, 27, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('齊藤 信雄', '准教授', 2, 24, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('本間 剛', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 由紀子', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('多賀谷 基博', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('白仁田 沙代子', '准教授', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('西川 雅美', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('船津 麻美', '准教授', 2, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小松 啓志', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('戸田 智之', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('シリポーン タオガァオ', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松田 翔風', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('張 田原', '助教', 2, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('明田川 正人', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('井原 郁夫', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 勉', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('太田 浩之', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('武田 雅敏', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('上村 靖司', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('南口 誠', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('木村 哲也', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('磯部 浩巳', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小林 泰秀', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('宮下 幸雄', '教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('本間 智之', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('倉橋 貴彦', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('勝身 俊之', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('會田 英雄', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鈴木 正太郎', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('庄司 観', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('溝尻 瑞枝', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('韋 冬', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('NGUYEN THI PHUONG MAI ', '准教授', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山下 健', '助教', 3, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('梅本 和希', '助教', 3, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('馬場 将亮', '助教', 3, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('横田 和哉', '助教', 3, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('原 圭祐', '助教', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('郭 妍伶', '助教', 3, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('陸 旻皎', '教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('細山田 得三', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('池田 隆明', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('豊田 浩史', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 修', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('下村 匠', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('岩崎 英治', '教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('佐野 可寸志', '教授', 4, 7, false, '原子力棟411の可能性あり');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小松 俊哉', '准教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('熊倉 俊郎', '准教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 一義', '准教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('宮下 剛', '准教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松田 曜子', '准教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('犬飼 直之', '准教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松川 寿也', '助教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中村 文則', '准教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('福元 豊', '准教授', 4, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('幡本 将史', '准教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('楊 宏選', '助教', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('渡利 高大', '助教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('坂田 健太', '助手', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 貴生', '助教授', 4, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('加藤 哲平', '講師', 4, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('李 志東', '教授', 5, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('塩野谷 明', '教授', 5, 19, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('野村 収作', '教授', 5, 3, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('秋元 頼孝', '准教授', 5, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('羽山 徹彩', '教授', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('伊藤 喜浩', '教授', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('綿引 宣道', '教授', 5, 9, false, 'メールアポ必須');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('西山 雄大', '教授', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大村 哲臣', '教授', 5, null, false, '居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鈴木 信貴', '准教授', 5, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大橋 智志', '准教授', 5, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('白川 智弘', '准教授', 5, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中平 勝子', '准教授', 5, 20, false, '居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('吉田 富美男', '助教', 5, 3, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鈴木 泉', '助教', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('畦原 宗之', '助教', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('永森 正仁', '助教', 5, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('安藤 雅洋', '助教', 5, 22, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 光子', '教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('原 信一郎', '教授', 6, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('加藤 有行', '教授', 6, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('若林 敦', '教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松原 浩', '教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('加納 満', '准教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('リー 飯塚 尚子', '准教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('伊藤 敦美', '准教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('藤井 数馬', '准教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山本 謙一郎', '准教授', 6, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('重田 謙', '准教授', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('永野 建二郎', '講師', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('五十嵐 啓太', '講師', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山口 勇気', '講師', 6, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('片野 洋平', '講師', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('ドライアー ブライアン', '助教', 6, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('江 偉華', '教授', 7, 12, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('末松 久幸', '教授', 7, 12, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鈴木 達也', '教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大塚 悟', '教授', 7, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('菊池 崇志', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鈴木 常生', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('村上 健太', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大場 恭子', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('竹澤 宏樹', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('太田 朋子', '准教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('松本 義伸', '助教', 7, 18, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('須貝 太一', '助教', 7, 12, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('立花 優', '助教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('ドウ テイ マイ ズン', '助教授', 7, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('VLAD CRISTIAN IULIAN', '教授', 8, null, false, '居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中川 匡弘', '教授', 8, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小林 高臣', '教授', 8, 8, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('改田 哲也', '教授', 8, 17, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小笠原 渉', '教授', 8, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山田 昇', '教授', 8, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中山 忠親', '教授', 8, 12, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('伊東 淳一', '教授', 8, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山口 隆司', '教授', 8, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('湯川 高志', '教授', 8, 9, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山崎 渉', '准教授', 8, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('牧 慎也', '准教授', 8, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('姫野 修司', '准教授', 8, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('佐々木 徹', '准教授', 8, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大沼 清', '准教授', 8, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('田中 諭', '准教授', 8, 27, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('門脇 敏', '教授', 9, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('三好 孝典', '教授', 9, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('阿部 雅二郎', '教授', 9, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('木村 哲也', '教授', 9, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山形 浩史', '教授', 9, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大塚 雄市', '准教授', 9, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('北條 理恵子', '准教授', 9, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('張 坤', '准教授', 9, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('吉田 昌弘', '技術職員', 10, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('安部 真', '技術職員', 10, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山田 修一', '技術職員', 10, 10, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('吉井 一夫', '技術職員', 10, 13, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山本 浩', '技術職員', 10, 3, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高田 晋', '技術職員', 10, 14, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 智', '技術職員', 10, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('渡邉 高子', '技術職員', 10, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中村 健', '技術職員', 10, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('豊田 英之', '技術職員', 10, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山口 貴幸', '技術職員', 10, 14, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('田中 徹', '技術職員', 10, 16, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('志田 暁雄', '技術職員', 10, 12, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('佐藤 賢太', '技術職員', 10, 13, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小池 孝侑', '技術職員', 10, 13, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('河原 夏江', '技術職員', 10, 27, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高橋 美幸', '技術職員', 10, 24, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('小杉 健一郎', '技術職員', 10, 24, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('高柳 充寛', '技術職員', 10, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('野田 浩平', '技術職員', 10, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山浦 賢太郎', '技術職員', 10, 5, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('近藤 みずき', '技術職員', 10, 6, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('草野 利樹', '技術職員', 10, null, false,'居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('上野 悠一', '技術職員', 10, null, false,'居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中山 佳子', '技術職員', 10, 7, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('山下 智樹', '特任准教授', 11, null, false,'居室不明');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('日下 佳祐', '特任講師', 11, 15, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('藤沢 慶', '特任講師', 11, 1, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('中田 大貴', '特任講師', 11, 2, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('鎌土 重晴', '学長', 12, 25, false, '秘書へアポ');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('和田 安弘', '副学長', 12, 4, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('秋山 和男', '理事・事務局長', 12, 26, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('梅田 実', '副学長', 12, 16, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('学生支援課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('学務課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('国際課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('総務課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('財務課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('研究・地域連携課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('入試課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('総合情報課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('施設課', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大学戦略課(3F)', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('大学戦略課(2F)', '事務', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('電気系', '系事務室', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('物質・材料・経営情報系', '系事務室', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('機械・建設事務室', '系事務室', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('生物系', '系事務室', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('環境事務室', '系事務室', 12, null, false, '');
INSERT into teachers (name, position, department_id, teacher_room_id, is_black,remark ) values ('芳賀 仁', '助教', 12, 5, false, '同窓会代表。局長が挨拶へ。学内募金は毎回断っている');
