import { ChakraProvider } from '@chakra-ui/react';
import { Table, Thead, Tbody, Tr, Th, Td, Flex, Spacer, Select } from '@chakra-ui/react';
import { Center, Box } from '@chakra-ui/react';
import Head from 'next/head';
import { RiAddCircleLine } from 'react-icons/ri';

import theme from '@assets/theme';
import EditButton from '@components/common/EditButton';
import Header from '@components/common/Header';
import RegistButton from '@components/common/RegistButton';

import type { NextPage } from 'next';
import clsx from 'clsx';
import MainLayout from '@/components/layout/MainLayout';

interface activity {
  id: number;
  sponsorID: number;
  sponsorStyleID: number;
  userID: number;
  isDone: boolean;
  createdAt: string;
  updated_At: string;
}

const activity: NextPage = () => {
  const activity = [
    {
      id: 1,
      sponsorID: 1,
      sponsorStyleID: 1,
      userID: 1,
      isDone: true,
      createdAt: '2022/3/1',
      updatedAt: '2022/3/2',
    },
    {
      id: 2,
      sponsorID: 2,
      sponsorStyleID: 2,
      userID: 2,
      isDone: false,
      createdAt: '2022/3/1',
      updatedAt: '2022/3/2',
    },
  ];
  return (
    <MainLayout>
      <Head>
        <title>協賛金一覧</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={clsx('text-center')}>
        <div className={clsx('m-10 px-10 boxShadow-base rounded-lg')}>
          <div className={clsx('mt-10 mx-5')}>
            <div className={clsx('flex')}>
              <div className={clsx('text-center mr-5 text-2x1 font-thin text-black')}>
                協賛金回収状況
              </div>
              <select className={'w-100'}>
                <option value='2021'>2021</option>
                <option value='2022'>2022</option>
              </select>
            </div>
            <div className={clsx('flex')}>
              <div>
                <RegistButton>
                  <RiAddCircleLine
                    size={20}
                    style={{
                      marginRight: 5,
                    }}
                  />
                  協賛スタイル登録
                </RegistButton>
              </div>
            </div>
          </div>
          <div className={clsx('p-5 mb-2')}>
            <table className={clsx('mb-5 w-full table-fixed border-collapse')}>
              <thead>
                <tr>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      ID
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      協賛ID
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm mr-1 text-black')}>
                      協賛スタイルID
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      ユーザーID
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      回収状況
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}></div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      作成日時
                    </div>
                  </th>
                  <th className={clsx('border-b-4 border-blue-400')}>
                    <div className={clsx('text-center text-sm text-black')}>
                      更新日時
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                {activity.map((activityItem) => (
                  <tr key={activityItem.id}>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.id}</div>
                    </td>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.sponsorID}</div>
                    </td>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.sponsorStyleID}</div>
                    </td>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.userID}</div>
                    </td>
                    <td>
                      {activityItem.isDone && <div className={clsx('text-center text-black')}>回収完了</div>}
                      {!activityItem.isDone && <div className={clsx('text-center text-black')}>未回収</div>}
                    </td>
                    <td>
                      <div className={clsx('text-center')}>
                        <EditButton />
                      </div>
                    </td>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.createdAt}</div>
                    </td>
                    <td>
                      <div className={clsx('text-center text-black')}>{activityItem.updatedAt}</div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default activity;
