import clsx from 'clsx';
import Head from 'next/head';
import { RiAddCircleLine } from 'react-icons/ri';

import MainLayout from '@/components/layout/MainLayout';
import EditButton from '@components/common/EditButton';
import RegistButton from '@components/common/RegistButton';

import type { NextPage } from 'next';


interface activity {
  id: number;
  sponsorID: number;
  sponsorStyleID: number;
  userID: number;
  isDone: boolean;
  createdAt: string;
  updated_At: string;
}

const activity: NextPage = () => {
  const activity = [
    {
      id: 1,
      sponsorID: 1,
      sponsorStyleID: 1,
      userID: 1,
      isDone: true,
      createdAt: '2022/3/1',
      updatedAt: '2022/3/2',
    },
    {
      id: 2,
      sponsorID: 2,
      sponsorStyleID: 2,
      userID: 2,
      isDone: false,
      createdAt: '2022/3/1',
      updatedAt: '2022/3/2',
    },
  ];
  return (
    <MainLayout>
      <Head>
        <title>協賛金一覧</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={clsx('text-center')}>
        <div className={clsx('boxShadow-base m-10 rounded-lg px-10')}>
          <div className={clsx('mx-5 mt-10')}>
            <div className={clsx('flex')}>
              <div className={clsx('text-2x1 text-black mr-5 text-center font-thin')}>
                協賛金回収状況
              </div>
              <select className={'w-100'}>
                <option value='2021'>2021</option>
                <option value='2022'>2022</option>
              </select>
            </div>
            <div className={clsx('flex')}>
              <div>
                <RegistButton>
                  <RiAddCircleLine
                    size={20}
                    style={{
                      marginRight: 5,
                    }}
                  />
                  協賛スタイル登録
                </RegistButton>
              </div>
            </div>
          </div>
          <div className={clsx('mb-2 p-5')}>
            <table className={clsx('mb-5 w-full table-fixed border-collapse')}>
              <thead>
                <tr>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>ID</div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>協賛ID</div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black mr-1 text-center text-sm')}>
                      協賛スタイルID
                    </div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>ユーザーID</div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>回収状況</div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}></div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>作成日時</div>
                  </th>
                  <th className={clsx('border-blue-400 border-b-4')}>
                    <div className={clsx('text-black text-center text-sm')}>更新日時</div>
                  </th>
                </tr>
              </thead>
              <tbody>
                {activity.map((activityItem) => (
                  <tr key={activityItem.id}>
                    <td>
                      <div className={clsx('text-black text-center')}>{activityItem.id}</div>
                    </td>
                    <td>
                      <div className={clsx('text-black text-center')}>{activityItem.sponsorID}</div>
                    </td>
                    <td>
                      <div className={clsx('text-black text-center')}>
                        {activityItem.sponsorStyleID}
                      </div>
                    </td>
                    <td>
                      <div className={clsx('text-black text-center')}>{activityItem.userID}</div>
                    </td>
                    <td>
                      {activityItem.isDone && (
                        <div className={clsx('text-black text-center')}>回収完了</div>
                      )}
                      {!activityItem.isDone && (
                        <div className={clsx('text-black text-center')}>未回収</div>
                      )}
                    </td>
                    <td>
                      <div className={clsx('text-center')}>
                        <EditButton />
                      </div>
                    </td>
                    <td>
                      <div className={clsx('text-black text-center')}>{activityItem.createdAt}</div>
                    </td>
                    <td>
                      <div className={clsx('text-black text-center')}>{activityItem.updatedAt}</div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default activity;
