name: Prettier

on:
  pull_request:
    branches:
      - develop

env:
  FILE_PATTERN: "view/next-project/src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
       - name: Prettier
        run: docker compose run --rm view npm run format
      - name: Lint
        run: docker compose run --rm view npm run lint
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change