name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "view/next-project/**"

env:
  CSR_API_URL: ${{secrets.CSR_API_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: view/next-project/package-lock.json
      - name: npm install
        working-directory: view/next-project
        run: npm install
      - name: Build
        working-directory: view/next-project
        run: npm run build
      - name: Prettier
        working-directory: view/next-project
        run: npm run format
      - name: Lint
        working-directory: view/next-project
        run: npm run lint:fix
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: formatted by workflow
