name: reviewdog
on:
  workflow_dispatch:
  pull_request:

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ./api
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          golangci_lint_flags: "--config=../.golangci.yml"
