name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ./api
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
# name: Lint

# on:
#   workflow_dispatch:
#   pull_request:

# jobs:
#   golangci:
#     name: lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code into the Go module directory
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           go-version: 1.20
#       - name: golangci-lint
#         uses: reviewdog/action-golangci-lint@v2
#         with:
#           github_token: ${{ github.token }}
#           level: info
#           workdir: ./api
#           fail_on_error: true
#           reporter: github-pr-review
#           timeout: 5m
