name: Lint

on:
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ github.token }}
          level: info
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: diff_context
          reporter: github-pr-review
          fail_on_error: true
