name: Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ github.token }}
          golangci_lint_flags: "--config=../.golangci.yml"
          level: info
          workdir: ./api
          fail_on_error: true
          reporter: github-pr-review
          timeout: 5m
